version: "3.7"

services:
  transmission:
    image: linuxserver/transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
    volumes:
      - ./.transmission/config:/config
      - ${TRANSMISSION_DOWNLOADS_DIR}:/downloads
    ports:
      - 9091:9091
      - ${TRANSMISSION_PORT}:${TRANSMISSION_PORT}
      - ${TRANSMISSION_PORT}:${TRANSMISSION_PORT}/udp
    restart: unless-stopped

  transmission-rss:
    build:
      context: ../transmission-rss
      dockerfile: Dockerfile
      args:
        - UID=${PUID}
        - GID=${PGID}
    volumes:
      - ./.transmission-rss/config/transmission-rss.conf:/etc/transmission-rss.conf
    restart: unless-stopped
