version: "3.7"

services:
  transmission:
    image: haugene/transmission-openvpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_WEB_UI=transmission-web-control
      - TRANSMISSION_DOWNLOAD_DIR=/downloads
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/data/transmission-home/unrar.sh
      - TRANSMISSION_PEER_PORT=${TRANSMISSION_PORT}
      - TRANSMISSION_DHT_ENABLED=false
      - TRANSMISSION_PEX_ENABLED=false
      - TRANSMISSION_LPD_ENABLED=false
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.0.0/16
    volumes:
      - ./.transmission/config:/data/transmission-home
      - ${TRANSMISSION_DOWNLOADS_DIR}:/downloads
      - /etc/localtime:/etc/localtime:ro
      - ./${OPENVPN_CONFIG}.ovpn:/etc/openvpn/${OPENVPN_CONFIG_DIR}/${OPENVPN_CONFIG}.ovpn
    ports:
      - 9091:9091
      - ${TRANSMISSION_PORT}:${TRANSMISSION_PORT}
      - ${TRANSMISSION_PORT}:${TRANSMISSION_PORT}/udp
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
    restart: unless-stopped

  #transmission-rss:
    #image: nning2/transmission-rss
    #volumes:
      #- ./.transmission-rss/config/transmission-rss.conf:/etc/transmission-rss.conf
      #restart: unless-stopped
